apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poll-ingress
  namespace: default
  labels:
    app: poll
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: poll.dop.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poll
            port:
              number: 80
