apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
  labels:
    app: redis
data:
  redis.conf: |
    # Redis configuration here
  REDIS_HOST: redis-service
