apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result-ingress
  namespace: default
  labels:
    app: ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: result.dop.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 80
