apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-public
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    nodePort: 30021
  - port: 8080
    name: admin
    protocol: TCP
    nodePort: 30042
  selector:
    app: traefik
  type: NodePort